2021-05-05 08:40:32,582 | 17534 | asyncio, __init__, 59 | DEBUG | Using selector: KqueueSelector
2021-05-05 08:40:32,583 | 17534 | proxy.proxy, open_connection, 243 | ERROR | Failed to connect to controller : [Errno 61] Connect call failed ('127.0.0.1', 6653)
2021-05-05 08:40:32,584 | 17534 | proxy.proxy, start_server, 132 | INFO | Server on ('127.0.0.1', 63333)
2021-05-05 08:40:32,584 | 17534 | proxy.proxy, start_server, 135 | INFO | Server serve forever ('127.0.0.1', 63333)
2021-05-05 08:40:41,485 | 17534 | proxy.proxy, handle_switch, 149 | INFO | Client None is connected
2021-05-05 08:40:41,485 | 17534 | proxy.proxy, handle_switch, 155 | DEBUG | waiting data ......
2021-05-05 08:40:41,486 | 17534 | proxy.proxy, handle_switch, 157 | DEBUG | read b's0'
2021-05-05 08:40:41,486 | 17534 | proxy.proxy, handle_switch, 155 | DEBUG | waiting data ......
2021-05-05 08:40:42,486 | 17534 | proxy.proxy, handle_switch, 149 | INFO | Client None is connected
2021-05-05 08:40:42,486 | 17534 | proxy.proxy, handle_switch, 155 | DEBUG | waiting data ......
2021-05-05 08:40:42,486 | 17534 | proxy.proxy, handle_switch, 157 | DEBUG | read b's1'
2021-05-05 08:40:42,486 | 17534 | proxy.proxy, handle_switch, 155 | DEBUG | waiting data ......
2021-05-05 08:40:43,489 | 17534 | proxy.proxy, handle_switch, 149 | INFO | Client None is connected
2021-05-05 08:40:43,490 | 17534 | proxy.proxy, handle_switch, 155 | DEBUG | waiting data ......
2021-05-05 08:40:43,490 | 17534 | proxy.proxy, handle_switch, 157 | DEBUG | read b's2'
2021-05-05 08:40:43,491 | 17534 | proxy.proxy, handle_switch, 155 | DEBUG | waiting data ......
2021-05-05 08:40:44,494 | 17534 | proxy.proxy, handle_switch, 149 | INFO | Client None is connected
2021-05-05 08:40:44,494 | 17534 | proxy.proxy, handle_switch, 155 | DEBUG | waiting data ......
2021-05-05 08:40:44,495 | 17534 | proxy.proxy, handle_switch, 157 | DEBUG | read b's3'
2021-05-05 08:40:44,495 | 17534 | proxy.proxy, handle_switch, 155 | DEBUG | waiting data ......
2021-05-05 08:40:45,495 | 17534 | proxy.proxy, handle_switch, 149 | INFO | Client None is connected
2021-05-05 08:40:45,496 | 17534 | proxy.proxy, handle_switch, 155 | DEBUG | waiting data ......
2021-05-05 08:40:45,496 | 17534 | proxy.proxy, handle_switch, 157 | DEBUG | read b's4'
2021-05-05 08:40:45,496 | 17534 | proxy.proxy, handle_switch, 155 | DEBUG | waiting data ......
2021-05-05 08:40:46,496 | 17534 | proxy.proxy, handle_switch, 149 | INFO | Client None is connected
2021-05-05 08:40:46,496 | 17534 | proxy.proxy, handle_switch, 155 | DEBUG | waiting data ......
2021-05-05 08:40:46,497 | 17534 | proxy.proxy, handle_switch, 157 | DEBUG | read b's5'
2021-05-05 08:40:46,497 | 17534 | proxy.proxy, handle_switch, 155 | DEBUG | waiting data ......
2021-05-05 08:40:47,497 | 17534 | proxy.proxy, handle_switch, 149 | INFO | Client None is connected
2021-05-05 08:40:47,498 | 17534 | proxy.proxy, handle_switch, 155 | DEBUG | waiting data ......
2021-05-05 08:40:47,498 | 17534 | proxy.proxy, handle_switch, 157 | DEBUG | read b's6'
2021-05-05 08:40:47,498 | 17534 | proxy.proxy, handle_switch, 155 | DEBUG | waiting data ......
2021-05-05 08:40:48,499 | 17534 | proxy.proxy, handle_switch, 149 | INFO | Client None is connected
2021-05-05 08:40:48,499 | 17534 | proxy.proxy, handle_switch, 155 | DEBUG | waiting data ......
2021-05-05 08:40:48,499 | 17534 | proxy.proxy, handle_switch, 157 | DEBUG | read b's7'
2021-05-05 08:40:48,499 | 17534 | proxy.proxy, handle_switch, 155 | DEBUG | waiting data ......
2021-05-05 08:40:49,499 | 17534 | proxy.proxy, handle_switch, 149 | INFO | Client None is connected
2021-05-05 08:40:49,500 | 17534 | proxy.proxy, handle_switch, 155 | DEBUG | waiting data ......
2021-05-05 08:40:49,500 | 17534 | proxy.proxy, handle_switch, 157 | DEBUG | read b's8'
2021-05-05 08:40:49,500 | 17534 | proxy.proxy, handle_switch, 155 | DEBUG | waiting data ......
2021-05-05 08:40:50,499 | 17534 | proxy.proxy, handle_switch, 149 | INFO | Client None is connected
2021-05-05 08:40:50,500 | 17534 | proxy.proxy, handle_switch, 155 | DEBUG | waiting data ......
2021-05-05 08:40:50,500 | 17534 | proxy.proxy, handle_switch, 157 | DEBUG | read b's9'
2021-05-05 08:40:50,500 | 17534 | proxy.proxy, handle_switch, 155 | DEBUG | waiting data ......
2021-05-05 08:41:53,519 | 17534 | proxy.proxy, handle_switch, 157 | DEBUG | read b''
2021-05-05 08:41:53,522 | 17534 | proxy.proxy, handle_switch, 159 | DEBUG | no data from switch read
2021-05-05 08:41:53,523 | 17534 | proxy.proxy, handle_switch, 170 | INFO | Close the connection and do exit processing
2021-05-05 08:41:53,525 | 17534 | proxy.proxy, handle_switch, 157 | DEBUG | read b''
2021-05-05 08:41:53,526 | 17534 | proxy.proxy, handle_switch, 159 | DEBUG | no data from switch read
2021-05-05 08:41:53,526 | 17534 | proxy.proxy, handle_switch, 170 | INFO | Close the connection and do exit processing
2021-05-05 08:41:53,528 | 17534 | asyncio, default_exception_handler, 1738 | ERROR | Task exception was never retrieved
future: <Task finished name='Task-10' coro=<SwitchHandler.handle_switch() done, defined at /Users/shu_ruhe/lesson/Network/ofcapture/proxy/proxy.py:138> exception=KeyError(None)>
Traceback (most recent call last):
  File "/Users/shu_ruhe/lesson/Network/ofcapture/proxy/proxy.py", line 171, in handle_switch
    self.switches.remove(peerneme)
KeyError: None
2021-05-05 08:41:53,535 | 17534 | proxy.proxy, handle_switch, 157 | DEBUG | read b''
2021-05-05 08:41:53,535 | 17534 | proxy.proxy, handle_switch, 159 | DEBUG | no data from switch read
2021-05-05 08:41:53,535 | 17534 | proxy.proxy, handle_switch, 170 | INFO | Close the connection and do exit processing
2021-05-05 08:41:53,535 | 17534 | asyncio, default_exception_handler, 1738 | ERROR | Task exception was never retrieved
future: <Task finished name='Task-13' coro=<SwitchHandler.handle_switch() done, defined at /Users/shu_ruhe/lesson/Network/ofcapture/proxy/proxy.py:138> exception=KeyError(None)>
Traceback (most recent call last):
  File "/Users/shu_ruhe/lesson/Network/ofcapture/proxy/proxy.py", line 171, in handle_switch
    self.switches.remove(peerneme)
KeyError: None
2021-05-05 08:41:53,536 | 17534 | proxy.proxy, handle_switch, 157 | DEBUG | read b''
2021-05-05 08:41:53,536 | 17534 | proxy.proxy, handle_switch, 159 | DEBUG | no data from switch read
2021-05-05 08:41:53,536 | 17534 | proxy.proxy, handle_switch, 170 | INFO | Close the connection and do exit processing
2021-05-05 08:41:53,537 | 17534 | asyncio, default_exception_handler, 1738 | ERROR | Task exception was never retrieved
future: <Task finished name='Task-16' coro=<SwitchHandler.handle_switch() done, defined at /Users/shu_ruhe/lesson/Network/ofcapture/proxy/proxy.py:138> exception=KeyError(None)>
Traceback (most recent call last):
  File "/Users/shu_ruhe/lesson/Network/ofcapture/proxy/proxy.py", line 171, in handle_switch
    self.switches.remove(peerneme)
KeyError: None
2021-05-05 08:41:53,537 | 17534 | proxy.proxy, handle_switch, 157 | DEBUG | read b''
2021-05-05 08:41:53,537 | 17534 | proxy.proxy, handle_switch, 159 | DEBUG | no data from switch read
2021-05-05 08:41:53,538 | 17534 | proxy.proxy, handle_switch, 170 | INFO | Close the connection and do exit processing
2021-05-05 08:41:53,538 | 17534 | asyncio, default_exception_handler, 1738 | ERROR | Task exception was never retrieved
future: <Task finished name='Task-19' coro=<SwitchHandler.handle_switch() done, defined at /Users/shu_ruhe/lesson/Network/ofcapture/proxy/proxy.py:138> exception=KeyError(None)>
Traceback (most recent call last):
  File "/Users/shu_ruhe/lesson/Network/ofcapture/proxy/proxy.py", line 171, in handle_switch
    self.switches.remove(peerneme)
KeyError: None
2021-05-05 08:41:53,540 | 17534 | proxy.proxy, handle_switch, 157 | DEBUG | read b''
2021-05-05 08:41:53,541 | 17534 | proxy.proxy, handle_switch, 159 | DEBUG | no data from switch read
2021-05-05 08:41:53,541 | 17534 | proxy.proxy, handle_switch, 170 | INFO | Close the connection and do exit processing
2021-05-05 08:41:53,541 | 17534 | asyncio, default_exception_handler, 1738 | ERROR | Task exception was never retrieved
future: <Task finished name='Task-22' coro=<SwitchHandler.handle_switch() done, defined at /Users/shu_ruhe/lesson/Network/ofcapture/proxy/proxy.py:138> exception=KeyError(None)>
Traceback (most recent call last):
  File "/Users/shu_ruhe/lesson/Network/ofcapture/proxy/proxy.py", line 171, in handle_switch
    self.switches.remove(peerneme)
KeyError: None
2021-05-05 08:41:53,544 | 17534 | proxy.proxy, handle_switch, 157 | DEBUG | read b''
2021-05-05 08:41:53,545 | 17534 | proxy.proxy, handle_switch, 159 | DEBUG | no data from switch read
2021-05-05 08:41:53,545 | 17534 | proxy.proxy, handle_switch, 170 | INFO | Close the connection and do exit processing
2021-05-05 08:41:53,545 | 17534 | asyncio, default_exception_handler, 1738 | ERROR | Task exception was never retrieved
future: <Task finished name='Task-25' coro=<SwitchHandler.handle_switch() done, defined at /Users/shu_ruhe/lesson/Network/ofcapture/proxy/proxy.py:138> exception=KeyError(None)>
Traceback (most recent call last):
  File "/Users/shu_ruhe/lesson/Network/ofcapture/proxy/proxy.py", line 171, in handle_switch
    self.switches.remove(peerneme)
KeyError: None
2021-05-05 08:41:53,546 | 17534 | proxy.proxy, handle_switch, 157 | DEBUG | read b''
2021-05-05 08:41:53,546 | 17534 | proxy.proxy, handle_switch, 159 | DEBUG | no data from switch read
2021-05-05 08:41:53,556 | 17534 | proxy.proxy, handle_switch, 170 | INFO | Close the connection and do exit processing
2021-05-05 08:41:53,556 | 17534 | asyncio, default_exception_handler, 1738 | ERROR | Task exception was never retrieved
future: <Task finished name='Task-28' coro=<SwitchHandler.handle_switch() done, defined at /Users/shu_ruhe/lesson/Network/ofcapture/proxy/proxy.py:138> exception=KeyError(None)>
Traceback (most recent call last):
  File "/Users/shu_ruhe/lesson/Network/ofcapture/proxy/proxy.py", line 171, in handle_switch
    self.switches.remove(peerneme)
KeyError: None
2021-05-05 08:41:53,557 | 17534 | proxy.proxy, handle_switch, 157 | DEBUG | read b''
2021-05-05 08:41:53,557 | 17534 | proxy.proxy, handle_switch, 159 | DEBUG | no data from switch read
2021-05-05 08:41:53,557 | 17534 | proxy.proxy, handle_switch, 170 | INFO | Close the connection and do exit processing
2021-05-05 08:41:53,558 | 17534 | asyncio, default_exception_handler, 1738 | ERROR | Task exception was never retrieved
future: <Task finished name='Task-31' coro=<SwitchHandler.handle_switch() done, defined at /Users/shu_ruhe/lesson/Network/ofcapture/proxy/proxy.py:138> exception=KeyError(None)>
Traceback (most recent call last):
  File "/Users/shu_ruhe/lesson/Network/ofcapture/proxy/proxy.py", line 171, in handle_switch
    self.switches.remove(peerneme)
KeyError: None
2021-05-05 08:41:53,560 | 17534 | proxy.proxy, handle_switch, 157 | DEBUG | read b''
2021-05-05 08:41:53,560 | 17534 | proxy.proxy, handle_switch, 159 | DEBUG | no data from switch read
2021-05-05 08:41:53,561 | 17534 | proxy.proxy, handle_switch, 170 | INFO | Close the connection and do exit processing
2021-05-05 08:41:53,561 | 17534 | asyncio, default_exception_handler, 1738 | ERROR | Task exception was never retrieved
future: <Task finished name='Task-34' coro=<SwitchHandler.handle_switch() done, defined at /Users/shu_ruhe/lesson/Network/ofcapture/proxy/proxy.py:138> exception=KeyError(None)>
Traceback (most recent call last):
  File "/Users/shu_ruhe/lesson/Network/ofcapture/proxy/proxy.py", line 171, in handle_switch
    self.switches.remove(peerneme)
KeyError: None
