2021-05-05 16:25:09,444 | 2997 | proxy.proxy, start_server, 199 | INFO | Server on ('127.0.0.1', 63333)
2021-05-05 16:25:09,444 | 2997 | proxy.proxy, start_server, 202 | INFO | Server serve forever ('127.0.0.1', 63333)
2021-05-05 16:25:56,984 | 3071 | asyncio, default_exception_handler, 1707 | ERROR | Task exception was never retrieved
future: <Task finished name='Task-3' coro=<SwitchHandler.start_server() done, defined at /home/shu/Network/ofcapture/proxy/proxy.py:192> exception=OSError(98, "error while attempting to bind on address ('127.0.0.1', 63333): address already in use")>
Traceback (most recent call last):
  File "/home/shu/Network/ofcapture/proxy/proxy.py", line 198, in start_server
    server = await asyncio.start_server(self.handle_switch, host=self.host, port=self.port)
  File "/usr/lib/python3.8/asyncio/streams.py", line 94, in start_server
    return await loop.create_server(factory, host, port, **kwds)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 1463, in create_server
    raise OSError(err.errno, 'error while attempting '
OSError: [Errno 98] error while attempting to bind on address ('127.0.0.1', 63333): address already in use
2021-05-05 16:25:57,004 | 3071 | asyncio, default_exception_handler, 1707 | ERROR | Task was destroyed but it is pending!
task: <Task pending name='Task-1' coro=<ObservableData.search_data() done, defined at /home/shu/Network/ofcapture/proxy/observable.py:45> wait_for=<Future cancelled>>
2021-05-05 16:26:24,774 | 2997 | proxy.proxy, handle_switch, 216 | INFO | Client ('127.0.0.1', 60998) is connected
2021-05-05 16:26:24,775 | 2997 | proxy.proxy, open_connection, 312 | ERROR | Failed to connect to controller : [Errno 111] Connect call failed ('127.0.0.1', 6633)
2021-05-05 16:26:24,775 | 2997 | proxy.proxy, create_channel, 147 | DEBUG | no connectable controller
2021-05-05 16:26:26,610 | 2997 | proxy.proxy, handle_switch, 216 | INFO | Client ('127.0.0.1', 32770) is connected
2021-05-05 16:26:26,611 | 2997 | proxy.proxy, open_connection, 312 | ERROR | Failed to connect to controller : [Errno 111] Connect call failed ('127.0.0.1', 6633)
2021-05-05 16:26:26,613 | 2997 | proxy.proxy, create_channel, 147 | DEBUG | no connectable controller
2021-05-05 16:26:26,614 | 2997 | proxy.proxy, handle_switch, 216 | INFO | Client ('127.0.0.1', 32774) is connected
2021-05-05 16:26:26,616 | 2997 | proxy.proxy, open_connection, 312 | ERROR | Failed to connect to controller : [Errno 111] Connect call failed ('127.0.0.1', 6633)
2021-05-05 16:26:26,647 | 2997 | proxy.proxy, create_channel, 147 | DEBUG | no connectable controller
2021-05-05 16:26:26,649 | 2997 | proxy.proxy, handle_switch, 216 | INFO | Client ('127.0.0.1', 32776) is connected
2021-05-05 16:26:26,656 | 2997 | proxy.proxy, open_connection, 312 | ERROR | Failed to connect to controller : [Errno 111] Connect call failed ('127.0.0.1', 6633)
2021-05-05 16:26:26,672 | 2997 | proxy.proxy, create_channel, 147 | DEBUG | no connectable controller
2021-05-05 16:26:27,691 | 2997 | proxy.proxy, handle_switch, 216 | INFO | Client ('127.0.0.1', 32782) is connected
2021-05-05 16:26:27,692 | 2997 | proxy.proxy, open_connection, 312 | ERROR | Failed to connect to controller : [Errno 111] Connect call failed ('127.0.0.1', 6633)
2021-05-05 16:26:27,693 | 2997 | proxy.proxy, create_channel, 147 | DEBUG | no connectable controller
2021-05-05 16:26:27,828 | 2997 | proxy.proxy, handle_switch, 216 | INFO | Client ('127.0.0.1', 32786) is connected
2021-05-05 16:26:27,830 | 2997 | proxy.proxy, open_connection, 312 | ERROR | Failed to connect to controller : [Errno 111] Connect call failed ('127.0.0.1', 6633)
2021-05-05 16:26:27,831 | 2997 | proxy.proxy, create_channel, 147 | DEBUG | no connectable controller
2021-05-05 16:26:27,832 | 2997 | proxy.proxy, handle_switch, 216 | INFO | Client ('127.0.0.1', 32790) is connected
2021-05-05 16:26:27,834 | 2997 | proxy.proxy, open_connection, 312 | ERROR | Failed to connect to controller : [Errno 111] Connect call failed ('127.0.0.1', 6633)
2021-05-05 16:26:27,834 | 2997 | proxy.proxy, create_channel, 147 | DEBUG | no connectable controller
2021-05-05 16:26:29,831 | 2997 | proxy.proxy, handle_switch, 216 | INFO | Client ('127.0.0.1', 32794) is connected
2021-05-05 16:26:29,837 | 2997 | proxy.proxy, open_connection, 312 | ERROR | Failed to connect to controller : [Errno 111] Connect call failed ('127.0.0.1', 6633)
2021-05-05 16:26:29,841 | 2997 | proxy.proxy, create_channel, 147 | DEBUG | no connectable controller
2021-05-05 16:26:30,332 | 2997 | proxy.proxy, handle_switch, 216 | INFO | Client ('127.0.0.1', 32798) is connected
2021-05-05 16:26:30,332 | 2997 | proxy.proxy, handle_switch, 216 | INFO | Client ('127.0.0.1', 32800) is connected
2021-05-05 16:26:30,333 | 2997 | proxy.proxy, open_connection, 312 | ERROR | Failed to connect to controller : [Errno 111] Connect call failed ('127.0.0.1', 6633)
2021-05-05 16:26:30,334 | 2997 | proxy.proxy, create_channel, 147 | DEBUG | no connectable controller
2021-05-05 16:26:30,334 | 2997 | proxy.proxy, open_connection, 312 | ERROR | Failed to connect to controller : [Errno 111] Connect call failed ('127.0.0.1', 6633)
2021-05-05 16:26:30,335 | 2997 | proxy.proxy, create_channel, 147 | DEBUG | no connectable controller
2021-05-05 16:26:34,341 | 2997 | proxy.proxy, handle_switch, 216 | INFO | Client ('127.0.0.1', 32808) is connected
2021-05-05 16:26:34,342 | 2997 | proxy.proxy, open_connection, 312 | ERROR | Failed to connect to controller : [Errno 111] Connect call failed ('127.0.0.1', 6633)
2021-05-05 16:26:34,342 | 2997 | proxy.proxy, create_channel, 147 | DEBUG | no connectable controller
2021-05-05 16:26:34,842 | 2997 | proxy.proxy, handle_switch, 216 | INFO | Client ('127.0.0.1', 32812) is connected
2021-05-05 16:26:34,844 | 2997 | proxy.proxy, handle_switch, 216 | INFO | Client ('127.0.0.1', 32814) is connected
2021-05-05 16:26:34,845 | 2997 | proxy.proxy, open_connection, 312 | ERROR | Failed to connect to controller : [Errno 111] Connect call failed ('127.0.0.1', 6633)
2021-05-05 16:26:34,847 | 2997 | proxy.proxy, create_channel, 147 | DEBUG | no connectable controller
2021-05-05 16:26:34,848 | 2997 | proxy.proxy, open_connection, 312 | ERROR | Failed to connect to controller : [Errno 111] Connect call failed ('127.0.0.1', 6633)
2021-05-05 16:26:34,849 | 2997 | proxy.proxy, create_channel, 147 | DEBUG | no connectable controller
2021-05-05 16:26:43,226 | 2997 | proxy.proxy, handle_switch, 216 | INFO | Client ('127.0.0.1', 32824) is connected
2021-05-05 16:26:43,229 | 2997 | proxy.proxy, handle_switch, 227 | DEBUG | waiting data ......
2021-05-05 16:26:43,230 | 2997 | proxy.proxy, handle_switch, 229 | DEBUG | read b'\x04\x00\x00\x10\x00\x00\x00\x10\x00\x01\x00\x08\x00\x00\x00\x10'
2021-05-05 16:26:43,230 | 2997 | proxy.proxy, send_to_controller, 72 | WARNING | Failed to send to controller : b'\x04\x00\x00\x10\x00\x00\x00\x10\x00\x01\x00\x08\x00\x00\x00\x10'
2021-05-05 16:26:43,231 | 2997 | proxy.proxy, handle_switch, 227 | DEBUG | waiting data ......
2021-05-05 16:26:43,232 | 2997 | proxy.proxy, handle_controller, 329 | INFO | connected Controller ('127.0.0.1', 6633)
2021-05-05 16:26:43,233 | 2997 | proxy.proxy, handle_controller, 334 | DEBUG | waiting data ......
2021-05-05 16:26:43,233 | 2997 | proxy.proxy, handle_controller, 336 | DEBUG | read b'\x04\x00\x00\x08\xe6\x19\x0b}'
2021-05-05 16:26:43,234 | 2997 | proxy.proxy, send_to_switch, 90 | WARNING | Failed to send to switch : b'\x04\x00\x00\x08\xe6\x19\x0b}'
2021-05-05 16:26:43,234 | 2997 | proxy.proxy, handle_controller, 334 | DEBUG | waiting data ......
2021-05-05 16:26:43,727 | 2997 | proxy.proxy, handle_switch, 216 | INFO | Client ('127.0.0.1', 32828) is connected
2021-05-05 16:26:43,730 | 2997 | proxy.proxy, handle_switch, 216 | INFO | Client ('127.0.0.1', 32830) is connected
2021-05-05 16:26:43,733 | 2997 | proxy.proxy, handle_switch, 227 | DEBUG | waiting data ......
2021-05-05 16:26:43,734 | 2997 | proxy.proxy, handle_switch, 229 | DEBUG | read b'\x04\x00\x00\x10\x00\x00\x00\x11\x00\x01\x00\x08\x00\x00\x00\x10'
2021-05-05 16:26:43,734 | 2997 | proxy.proxy, send_to_controller, 72 | WARNING | Failed to send to controller : b'\x04\x00\x00\x10\x00\x00\x00\x11\x00\x01\x00\x08\x00\x00\x00\x10'
2021-05-05 16:26:43,735 | 2997 | proxy.proxy, handle_switch, 227 | DEBUG | waiting data ......
2021-05-05 16:26:43,736 | 2997 | proxy.proxy, handle_switch, 227 | DEBUG | waiting data ......
2021-05-05 16:26:43,736 | 2997 | proxy.proxy, handle_switch, 229 | DEBUG | read b'\x04\x00\x00\x10\x00\x00\x00\x12\x00\x01\x00\x08\x00\x00\x00\x10'
2021-05-05 16:26:43,737 | 2997 | proxy.proxy, send_to_controller, 72 | WARNING | Failed to send to controller : b'\x04\x00\x00\x10\x00\x00\x00\x12\x00\x01\x00\x08\x00\x00\x00\x10'
2021-05-05 16:26:43,737 | 2997 | proxy.proxy, handle_switch, 227 | DEBUG | waiting data ......
2021-05-05 16:26:43,742 | 2997 | proxy.proxy, handle_controller, 329 | INFO | connected Controller ('127.0.0.1', 6633)
2021-05-05 16:26:43,743 | 2997 | proxy.proxy, handle_controller, 334 | DEBUG | waiting data ......
2021-05-05 16:26:43,743 | 2997 | proxy.proxy, handle_controller, 336 | DEBUG | read b'\x04\x00\x00\x08c(\x08\xac'
2021-05-05 16:26:43,744 | 2997 | proxy.proxy, send_to_switch, 90 | WARNING | Failed to send to switch : b'\x04\x00\x00\x08c(\x08\xac'
2021-05-05 16:26:43,748 | 2997 | proxy.proxy, handle_controller, 334 | DEBUG | waiting data ......
2021-05-05 16:26:43,749 | 2997 | proxy.proxy, handle_controller, 329 | INFO | connected Controller ('127.0.0.1', 6633)
2021-05-05 16:26:43,751 | 2997 | proxy.proxy, handle_controller, 334 | DEBUG | waiting data ......
2021-05-05 16:26:43,752 | 2997 | proxy.proxy, handle_controller, 336 | DEBUG | read b'\x04\x00\x00\x08\x9b\xc9\xaaH'
2021-05-05 16:26:43,752 | 2997 | proxy.proxy, send_to_switch, 90 | WARNING | Failed to send to switch : b'\x04\x00\x00\x08\x9b\xc9\xaaH'
2021-05-05 16:26:43,758 | 2997 | proxy.proxy, handle_controller, 334 | DEBUG | waiting data ......
2021-05-05 16:26:51,238 | 2997 | proxy.proxy, handle_switch, 229 | DEBUG | read b''
2021-05-05 16:26:51,240 | 2997 | proxy.proxy, handle_switch, 231 | DEBUG | no data from switch read
2021-05-05 16:26:51,240 | 2997 | proxy.proxy, handle_switch, 246 | INFO | Close the connection and do exit processing
2021-05-05 16:26:51,740 | 2997 | proxy.proxy, handle_switch, 229 | DEBUG | read b''
2021-05-05 16:26:51,743 | 2997 | proxy.proxy, handle_switch, 231 | DEBUG | no data from switch read
2021-05-05 16:26:51,744 | 2997 | proxy.proxy, handle_switch, 246 | INFO | Close the connection and do exit processing
2021-05-05 16:26:51,745 | 2997 | proxy.proxy, handle_switch, 229 | DEBUG | read b''
2021-05-05 16:26:51,746 | 2997 | proxy.proxy, handle_switch, 231 | DEBUG | no data from switch read
2021-05-05 16:26:51,746 | 2997 | proxy.proxy, handle_switch, 246 | INFO | Close the connection and do exit processing
2021-05-05 16:26:59,254 | 2997 | proxy.proxy, handle_switch, 216 | INFO | Client ('127.0.0.1', 32838) is connected
2021-05-05 16:26:59,255 | 2997 | proxy.proxy, handle_switch, 227 | DEBUG | waiting data ......
2021-05-05 16:26:59,257 | 2997 | proxy.proxy, handle_controller, 329 | INFO | connected Controller ('127.0.0.1', 6633)
2021-05-05 16:26:59,258 | 2997 | proxy.proxy, handle_controller, 334 | DEBUG | waiting data ......
2021-05-05 16:26:59,261 | 2997 | proxy.proxy, handle_controller, 336 | DEBUG | read b'\x04\x00\x00\x08\x7f\xb9\xb6\xa5'
2021-05-05 16:26:59,267 | 2997 | proxy.proxy, send_to_switch, 90 | WARNING | Failed to send to switch : b'\x04\x00\x00\x08\x7f\xb9\xb6\xa5'
2021-05-05 16:26:59,268 | 2997 | proxy.proxy, handle_controller, 334 | DEBUG | waiting data ......
2021-05-05 16:26:59,274 | 2997 | proxy.proxy, handle_switch, 229 | DEBUG | read b'\x04\x00\x00\x10\x00\x00\x00\x13\x00\x01\x00\x08\x00\x00\x00\x10'
2021-05-05 16:26:59,275 | 2997 | proxy.proxy, send_to_controller, 72 | WARNING | Failed to send to controller : b'\x04\x00\x00\x10\x00\x00\x00\x13\x00\x01\x00\x08\x00\x00\x00\x10'
2021-05-05 16:26:59,276 | 2997 | proxy.proxy, handle_switch, 227 | DEBUG | waiting data ......
2021-05-05 16:26:59,755 | 2997 | proxy.proxy, handle_switch, 216 | INFO | Client ('127.0.0.1', 32842) is connected
2021-05-05 16:26:59,758 | 2997 | proxy.proxy, handle_controller, 349 | INFO | Close the connection and do exit processing
2021-05-05 16:26:59,759 | 2997 | asyncio, default_exception_handler, 1707 | ERROR | Task was destroyed but it is pending!
task: <Task pending name='Task-33' coro=<ControllerHandler.handle_controller() done, defined at /home/shu/Network/ofcapture/proxy/proxy.py:317> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7faccdd595e0>()]>>
2021-05-05 16:26:59,762 | 2997 | proxy.proxy, handle_controller, 349 | INFO | Close the connection and do exit processing
2021-05-05 16:26:59,763 | 2997 | asyncio, default_exception_handler, 1707 | ERROR | Task was destroyed but it is pending!
task: <Task pending name='Task-38' coro=<ControllerHandler.handle_controller() done, defined at /home/shu/Network/ofcapture/proxy/proxy.py:317> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7faccdd59d00>()]>>
2021-05-05 16:26:59,763 | 2997 | proxy.proxy, handle_controller, 349 | INFO | Close the connection and do exit processing
2021-05-05 16:26:59,764 | 2997 | asyncio, default_exception_handler, 1707 | ERROR | Task was destroyed but it is pending!
task: <Task pending name='Task-39' coro=<ControllerHandler.handle_controller() done, defined at /home/shu/Network/ofcapture/proxy/proxy.py:317> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7faccdd59b50>()]>>
2021-05-05 16:26:59,765 | 2997 | proxy.proxy, handle_switch, 216 | INFO | Client ('127.0.0.1', 32844) is connected
2021-05-05 16:26:59,771 | 2997 | proxy.proxy, handle_switch, 227 | DEBUG | waiting data ......
2021-05-05 16:26:59,772 | 2997 | proxy.proxy, handle_switch, 229 | DEBUG | read b'\x04\x00\x00\x10\x00\x00\x00\x14\x00\x01\x00\x08\x00\x00\x00\x10'
2021-05-05 16:26:59,773 | 2997 | proxy.proxy, send_to_controller, 72 | WARNING | Failed to send to controller : b'\x04\x00\x00\x10\x00\x00\x00\x14\x00\x01\x00\x08\x00\x00\x00\x10'
2021-05-05 16:26:59,773 | 2997 | proxy.proxy, handle_switch, 227 | DEBUG | waiting data ......
2021-05-05 16:26:59,779 | 2997 | proxy.proxy, handle_switch, 227 | DEBUG | waiting data ......
2021-05-05 16:26:59,780 | 2997 | proxy.proxy, handle_switch, 229 | DEBUG | read b'\x04\x00\x00\x10\x00\x00\x00\x15\x00\x01\x00\x08\x00\x00\x00\x10'
2021-05-05 16:26:59,782 | 2997 | proxy.proxy, send_to_controller, 72 | WARNING | Failed to send to controller : b'\x04\x00\x00\x10\x00\x00\x00\x15\x00\x01\x00\x08\x00\x00\x00\x10'
2021-05-05 16:26:59,791 | 2997 | proxy.proxy, handle_switch, 227 | DEBUG | waiting data ......
2021-05-05 16:26:59,795 | 2997 | proxy.proxy, handle_controller, 329 | INFO | connected Controller ('127.0.0.1', 6633)
2021-05-05 16:26:59,797 | 2997 | proxy.proxy, handle_controller, 334 | DEBUG | waiting data ......
2021-05-05 16:26:59,800 | 2997 | proxy.proxy, handle_controller, 336 | DEBUG | read b'\x04\x00\x00\x08\x84\xf52s'
2021-05-05 16:26:59,801 | 2997 | proxy.proxy, send_to_switch, 90 | WARNING | Failed to send to switch : b'\x04\x00\x00\x08\x84\xf52s'
2021-05-05 16:26:59,801 | 2997 | proxy.proxy, handle_controller, 334 | DEBUG | waiting data ......
2021-05-05 16:26:59,802 | 2997 | proxy.proxy, handle_controller, 329 | INFO | connected Controller ('127.0.0.1', 6633)
2021-05-05 16:26:59,802 | 2997 | proxy.proxy, handle_controller, 334 | DEBUG | waiting data ......
2021-05-05 16:26:59,803 | 2997 | proxy.proxy, handle_controller, 336 | DEBUG | read b'\x04\x00\x00\x08\xdf^\x8f\x16'
2021-05-05 16:26:59,803 | 2997 | proxy.proxy, send_to_switch, 90 | WARNING | Failed to send to switch : b'\x04\x00\x00\x08\xdf^\x8f\x16'
2021-05-05 16:26:59,804 | 2997 | proxy.proxy, handle_controller, 334 | DEBUG | waiting data ......
2021-05-05 16:27:07,270 | 2997 | proxy.proxy, handle_switch, 229 | DEBUG | read b''
2021-05-05 16:27:07,271 | 2997 | proxy.proxy, handle_switch, 231 | DEBUG | no data from switch read
2021-05-05 16:27:07,272 | 2997 | proxy.proxy, handle_switch, 246 | INFO | Close the connection and do exit processing
2021-05-05 16:27:07,772 | 2997 | proxy.proxy, handle_switch, 229 | DEBUG | read b''
2021-05-05 16:27:07,772 | 2997 | proxy.proxy, handle_switch, 231 | DEBUG | no data from switch read
2021-05-05 16:27:07,773 | 2997 | proxy.proxy, handle_switch, 246 | INFO | Close the connection and do exit processing
2021-05-05 16:27:07,774 | 2997 | proxy.proxy, handle_switch, 229 | DEBUG | read b''
2021-05-05 16:27:07,774 | 2997 | proxy.proxy, handle_switch, 231 | DEBUG | no data from switch read
2021-05-05 16:27:07,775 | 2997 | proxy.proxy, handle_switch, 246 | INFO | Close the connection and do exit processing
2021-05-05 16:27:15,287 | 2997 | proxy.proxy, handle_switch, 216 | INFO | Client ('127.0.0.1', 32852) is connected
2021-05-05 16:27:15,294 | 2997 | proxy.proxy, handle_switch, 227 | DEBUG | waiting data ......
2021-05-05 16:27:15,295 | 2997 | proxy.proxy, handle_switch, 229 | DEBUG | read b'\x04\x00\x00\x10\x00\x00\x00\x16\x00\x01\x00\x08\x00\x00\x00\x10'
2021-05-05 16:27:15,295 | 2997 | proxy.proxy, send_to_controller, 72 | WARNING | Failed to send to controller : b'\x04\x00\x00\x10\x00\x00\x00\x16\x00\x01\x00\x08\x00\x00\x00\x10'
2021-05-05 16:27:15,296 | 2997 | proxy.proxy, handle_switch, 227 | DEBUG | waiting data ......
2021-05-05 16:27:15,296 | 2997 | proxy.proxy, handle_controller, 329 | INFO | connected Controller ('127.0.0.1', 6633)
2021-05-05 16:27:15,296 | 2997 | proxy.proxy, handle_controller, 334 | DEBUG | waiting data ......
2021-05-05 16:27:15,297 | 2997 | proxy.proxy, handle_controller, 336 | DEBUG | read b'\x04\x00\x00\x08\xc1\x02\xc5\x9c'
2021-05-05 16:27:15,297 | 2997 | proxy.proxy, send_to_switch, 90 | WARNING | Failed to send to switch : b'\x04\x00\x00\x08\xc1\x02\xc5\x9c'
2021-05-05 16:27:15,300 | 2997 | proxy.proxy, handle_controller, 334 | DEBUG | waiting data ......
2021-05-05 16:27:15,789 | 2997 | proxy.proxy, handle_switch, 216 | INFO | Client ('127.0.0.1', 32856) is connected
2021-05-05 16:27:15,791 | 2997 | proxy.proxy, handle_switch, 216 | INFO | Client ('127.0.0.1', 32858) is connected
2021-05-05 16:27:15,793 | 2997 | proxy.proxy, handle_switch, 227 | DEBUG | waiting data ......
2021-05-05 16:27:15,794 | 2997 | proxy.proxy, handle_switch, 229 | DEBUG | read b'\x04\x00\x00\x10\x00\x00\x00\x17\x00\x01\x00\x08\x00\x00\x00\x10'
2021-05-05 16:27:15,794 | 2997 | proxy.proxy, send_to_controller, 72 | WARNING | Failed to send to controller : b'\x04\x00\x00\x10\x00\x00\x00\x17\x00\x01\x00\x08\x00\x00\x00\x10'
2021-05-05 16:27:15,795 | 2997 | proxy.proxy, handle_switch, 227 | DEBUG | waiting data ......
2021-05-05 16:27:15,795 | 2997 | proxy.proxy, handle_switch, 227 | DEBUG | waiting data ......
2021-05-05 16:27:15,796 | 2997 | proxy.proxy, handle_switch, 229 | DEBUG | read b'\x04\x00\x00\x10\x00\x00\x00\x18\x00\x01\x00\x08\x00\x00\x00\x10'
2021-05-05 16:27:15,796 | 2997 | proxy.proxy, send_to_controller, 72 | WARNING | Failed to send to controller : b'\x04\x00\x00\x10\x00\x00\x00\x18\x00\x01\x00\x08\x00\x00\x00\x10'
2021-05-05 16:27:15,796 | 2997 | proxy.proxy, handle_switch, 227 | DEBUG | waiting data ......
2021-05-05 16:27:15,797 | 2997 | proxy.proxy, handle_controller, 329 | INFO | connected Controller ('127.0.0.1', 6633)
2021-05-05 16:27:15,797 | 2997 | proxy.proxy, handle_controller, 334 | DEBUG | waiting data ......
2021-05-05 16:27:15,798 | 2997 | proxy.proxy, handle_controller, 336 | DEBUG | read b'\x04\x00\x00\x08\xb5\x99\xf0z'
2021-05-05 16:27:15,798 | 2997 | proxy.proxy, send_to_switch, 90 | WARNING | Failed to send to switch : b'\x04\x00\x00\x08\xb5\x99\xf0z'
2021-05-05 16:27:15,799 | 2997 | proxy.proxy, handle_controller, 334 | DEBUG | waiting data ......
2021-05-05 16:27:15,802 | 2997 | proxy.proxy, handle_controller, 329 | INFO | connected Controller ('127.0.0.1', 6633)
2021-05-05 16:27:15,802 | 2997 | proxy.proxy, handle_controller, 334 | DEBUG | waiting data ......
2021-05-05 16:27:15,802 | 2997 | proxy.proxy, handle_controller, 336 | DEBUG | read b'\x04\x00\x00\x08\xb4\x06\xac\xd1'
2021-05-05 16:27:15,803 | 2997 | proxy.proxy, send_to_switch, 90 | WARNING | Failed to send to switch : b'\x04\x00\x00\x08\xb4\x06\xac\xd1'
2021-05-05 16:27:15,803 | 2997 | proxy.proxy, handle_controller, 334 | DEBUG | waiting data ......
2021-05-05 16:27:23,302 | 2997 | proxy.proxy, handle_switch, 229 | DEBUG | read b''
2021-05-05 16:27:23,302 | 2997 | proxy.proxy, handle_switch, 231 | DEBUG | no data from switch read
2021-05-05 16:27:23,303 | 2997 | proxy.proxy, handle_switch, 246 | INFO | Close the connection and do exit processing
2021-05-05 16:27:23,803 | 2997 | proxy.proxy, handle_switch, 229 | DEBUG | read b''
2021-05-05 16:27:23,803 | 2997 | proxy.proxy, handle_switch, 231 | DEBUG | no data from switch read
2021-05-05 16:27:23,804 | 2997 | proxy.proxy, handle_switch, 246 | INFO | Close the connection and do exit processing
2021-05-05 16:27:23,804 | 2997 | proxy.proxy, handle_switch, 229 | DEBUG | read b''
2021-05-05 16:27:23,805 | 2997 | proxy.proxy, handle_switch, 231 | DEBUG | no data from switch read
2021-05-05 16:27:23,805 | 2997 | proxy.proxy, handle_switch, 246 | INFO | Close the connection and do exit processing
2021-05-05 16:27:31,315 | 2997 | proxy.proxy, handle_switch, 216 | INFO | Client ('127.0.0.1', 32866) is connected
2021-05-05 16:27:31,318 | 2997 | proxy.proxy, handle_switch, 227 | DEBUG | waiting data ......
2021-05-05 16:27:31,319 | 2997 | proxy.proxy, handle_switch, 229 | DEBUG | read b'\x04\x00\x00\x10\x00\x00\x00\x19\x00\x01\x00\x08\x00\x00\x00\x10'
2021-05-05 16:27:31,320 | 2997 | proxy.proxy, send_to_controller, 72 | WARNING | Failed to send to controller : b'\x04\x00\x00\x10\x00\x00\x00\x19\x00\x01\x00\x08\x00\x00\x00\x10'
2021-05-05 16:27:31,320 | 2997 | proxy.proxy, handle_switch, 227 | DEBUG | waiting data ......
2021-05-05 16:27:31,321 | 2997 | proxy.proxy, handle_controller, 329 | INFO | connected Controller ('127.0.0.1', 6633)
2021-05-05 16:27:31,321 | 2997 | proxy.proxy, handle_controller, 334 | DEBUG | waiting data ......
2021-05-05 16:27:31,322 | 2997 | proxy.proxy, handle_controller, 336 | DEBUG | read b'\x04\x00\x00\x08Iy\xafs'
2021-05-05 16:27:31,322 | 2997 | proxy.proxy, send_to_switch, 90 | WARNING | Failed to send to switch : b'\x04\x00\x00\x08Iy\xafs'
2021-05-05 16:27:31,323 | 2997 | proxy.proxy, handle_controller, 334 | DEBUG | waiting data ......
2021-05-05 16:27:31,815 | 2997 | proxy.proxy, handle_switch, 216 | INFO | Client ('127.0.0.1', 32870) is connected
2021-05-05 16:27:31,817 | 2997 | proxy.proxy, handle_switch, 216 | INFO | Client ('127.0.0.1', 32872) is connected
2021-05-05 16:27:31,820 | 2997 | proxy.proxy, handle_switch, 227 | DEBUG | waiting data ......
2021-05-05 16:27:31,821 | 2997 | proxy.proxy, handle_switch, 229 | DEBUG | read b'\x04\x00\x00\x10\x00\x00\x00\x1a\x00\x01\x00\x08\x00\x00\x00\x10'
2021-05-05 16:27:31,821 | 2997 | proxy.proxy, send_to_controller, 72 | WARNING | Failed to send to controller : b'\x04\x00\x00\x10\x00\x00\x00\x1a\x00\x01\x00\x08\x00\x00\x00\x10'
2021-05-05 16:27:31,822 | 2997 | proxy.proxy, handle_switch, 227 | DEBUG | waiting data ......
2021-05-05 16:27:31,822 | 2997 | proxy.proxy, handle_switch, 227 | DEBUG | waiting data ......
2021-05-05 16:27:31,822 | 2997 | proxy.proxy, handle_switch, 229 | DEBUG | read b'\x04\x00\x00\x10\x00\x00\x00\x1b\x00\x01\x00\x08\x00\x00\x00\x10'
2021-05-05 16:27:31,823 | 2997 | proxy.proxy, send_to_controller, 72 | WARNING | Failed to send to controller : b'\x04\x00\x00\x10\x00\x00\x00\x1b\x00\x01\x00\x08\x00\x00\x00\x10'
2021-05-05 16:27:31,823 | 2997 | proxy.proxy, handle_switch, 227 | DEBUG | waiting data ......
2021-05-05 16:27:31,824 | 2997 | proxy.proxy, handle_controller, 329 | INFO | connected Controller ('127.0.0.1', 6633)
2021-05-05 16:27:31,824 | 2997 | proxy.proxy, handle_controller, 334 | DEBUG | waiting data ......
2021-05-05 16:27:31,825 | 2997 | proxy.proxy, handle_controller, 336 | DEBUG | read b'\x04\x00\x00\x08\xf2.\xc8^'
2021-05-05 16:27:31,825 | 2997 | proxy.proxy, send_to_switch, 90 | WARNING | Failed to send to switch : b'\x04\x00\x00\x08\xf2.\xc8^'
2021-05-05 16:27:31,825 | 2997 | proxy.proxy, handle_controller, 334 | DEBUG | waiting data ......
2021-05-05 16:27:31,833 | 2997 | proxy.proxy, handle_controller, 329 | INFO | connected Controller ('127.0.0.1', 6633)
2021-05-05 16:27:31,833 | 2997 | proxy.proxy, handle_controller, 334 | DEBUG | waiting data ......
2021-05-05 16:27:31,834 | 2997 | proxy.proxy, handle_controller, 336 | DEBUG | read b'\x04\x00\x00\x08\x00$\x8e\xba'
2021-05-05 16:27:31,835 | 2997 | proxy.proxy, send_to_switch, 90 | WARNING | Failed to send to switch : b'\x04\x00\x00\x08\x00$\x8e\xba'
2021-05-05 16:27:31,835 | 2997 | proxy.proxy, handle_controller, 334 | DEBUG | waiting data ......
2021-05-05 16:27:39,328 | 2997 | proxy.proxy, handle_switch, 229 | DEBUG | read b''
2021-05-05 16:27:39,328 | 2997 | proxy.proxy, handle_switch, 231 | DEBUG | no data from switch read
2021-05-05 16:27:39,329 | 2997 | proxy.proxy, handle_switch, 246 | INFO | Close the connection and do exit processing
2021-05-05 16:27:39,829 | 2997 | proxy.proxy, handle_switch, 229 | DEBUG | read b''
2021-05-05 16:27:39,830 | 2997 | proxy.proxy, handle_switch, 231 | DEBUG | no data from switch read
2021-05-05 16:27:39,830 | 2997 | proxy.proxy, handle_switch, 246 | INFO | Close the connection and do exit processing
2021-05-05 16:27:39,830 | 2997 | proxy.proxy, handle_switch, 229 | DEBUG | read b''
2021-05-05 16:27:39,831 | 2997 | proxy.proxy, handle_switch, 231 | DEBUG | no data from switch read
2021-05-05 16:27:39,831 | 2997 | proxy.proxy, handle_switch, 246 | INFO | Close the connection and do exit processing
2021-05-05 16:27:47,339 | 2997 | proxy.proxy, handle_switch, 216 | INFO | Client ('127.0.0.1', 32882) is connected
2021-05-05 16:27:47,360 | 2997 | proxy.proxy, handle_switch, 227 | DEBUG | waiting data ......
2021-05-05 16:27:47,371 | 2997 | proxy.proxy, handle_switch, 229 | DEBUG | read b'\x04\x00\x00\x10\x00\x00\x00\x1c\x00\x01\x00\x08\x00\x00\x00\x10'
2021-05-05 16:27:47,375 | 2997 | proxy.proxy, send_to_controller, 72 | WARNING | Failed to send to controller : b'\x04\x00\x00\x10\x00\x00\x00\x1c\x00\x01\x00\x08\x00\x00\x00\x10'
2021-05-05 16:27:47,377 | 2997 | proxy.proxy, handle_switch, 227 | DEBUG | waiting data ......
2021-05-05 16:27:47,383 | 2997 | proxy.proxy, handle_controller, 329 | INFO | connected Controller ('127.0.0.1', 6633)
2021-05-05 16:27:47,386 | 2997 | proxy.proxy, handle_controller, 334 | DEBUG | waiting data ......
2021-05-05 16:27:47,394 | 2997 | proxy.proxy, handle_controller, 336 | DEBUG | read b'\x04\x00\x00\x08d4h\xf9'
2021-05-05 16:27:47,401 | 2997 | proxy.proxy, send_to_switch, 90 | WARNING | Failed to send to switch : b'\x04\x00\x00\x08d4h\xf9'
2021-05-05 16:27:47,414 | 2997 | proxy.proxy, handle_controller, 334 | DEBUG | waiting data ......
2021-05-05 16:27:47,836 | 2997 | proxy.proxy, handle_switch, 216 | INFO | Client ('127.0.0.1', 32886) is connected
2021-05-05 16:27:47,838 | 2997 | proxy.proxy, handle_switch, 216 | INFO | Client ('127.0.0.1', 32888) is connected
2021-05-05 16:27:47,840 | 2997 | proxy.proxy, handle_switch, 227 | DEBUG | waiting data ......
2021-05-05 16:27:47,842 | 2997 | proxy.proxy, handle_switch, 229 | DEBUG | read b'\x04\x00\x00\x10\x00\x00\x00\x1d\x00\x01\x00\x08\x00\x00\x00\x10'
2021-05-05 16:27:47,842 | 2997 | proxy.proxy, send_to_controller, 72 | WARNING | Failed to send to controller : b'\x04\x00\x00\x10\x00\x00\x00\x1d\x00\x01\x00\x08\x00\x00\x00\x10'
2021-05-05 16:27:47,846 | 2997 | proxy.proxy, handle_switch, 227 | DEBUG | waiting data ......
2021-05-05 16:27:47,847 | 2997 | proxy.proxy, handle_switch, 227 | DEBUG | waiting data ......
2021-05-05 16:27:47,849 | 2997 | proxy.proxy, handle_switch, 229 | DEBUG | read b'\x04\x00\x00\x10\x00\x00\x00\x1e\x00\x01\x00\x08\x00\x00\x00\x10'
2021-05-05 16:27:47,850 | 2997 | proxy.proxy, send_to_controller, 72 | WARNING | Failed to send to controller : b'\x04\x00\x00\x10\x00\x00\x00\x1e\x00\x01\x00\x08\x00\x00\x00\x10'
2021-05-05 16:27:47,851 | 2997 | proxy.proxy, handle_switch, 227 | DEBUG | waiting data ......
2021-05-05 16:27:47,854 | 2997 | proxy.proxy, handle_controller, 329 | INFO | connected Controller ('127.0.0.1', 6633)
2021-05-05 16:27:47,855 | 2997 | proxy.proxy, handle_controller, 334 | DEBUG | waiting data ......
2021-05-05 16:27:47,856 | 2997 | proxy.proxy, handle_controller, 336 | DEBUG | read b'\x04\x00\x00\x08\ny/\x1c'
2021-05-05 16:27:47,856 | 2997 | proxy.proxy, send_to_switch, 90 | WARNING | Failed to send to switch : b'\x04\x00\x00\x08\ny/\x1c'
2021-05-05 16:27:47,857 | 2997 | proxy.proxy, handle_controller, 334 | DEBUG | waiting data ......
2021-05-05 16:27:47,858 | 2997 | proxy.proxy, handle_controller, 329 | INFO | connected Controller ('127.0.0.1', 6633)
2021-05-05 16:27:47,870 | 2997 | proxy.proxy, handle_controller, 334 | DEBUG | waiting data ......
2021-05-05 16:27:47,871 | 2997 | proxy.proxy, handle_controller, 336 | DEBUG | read b'\x04\x00\x00\x08\xd9\x82\x95G'
2021-05-05 16:27:47,873 | 2997 | proxy.proxy, send_to_switch, 90 | WARNING | Failed to send to switch : b'\x04\x00\x00\x08\xd9\x82\x95G'
2021-05-05 16:27:47,874 | 2997 | proxy.proxy, handle_controller, 334 | DEBUG | waiting data ......
2021-05-05 16:27:55,351 | 2997 | proxy.proxy, handle_switch, 229 | DEBUG | read b''
2021-05-05 16:27:55,353 | 2997 | proxy.proxy, handle_switch, 231 | DEBUG | no data from switch read
2021-05-05 16:27:55,354 | 2997 | proxy.proxy, handle_switch, 246 | INFO | Close the connection and do exit processing
2021-05-05 16:27:55,852 | 2997 | proxy.proxy, handle_switch, 229 | DEBUG | read b''
2021-05-05 16:27:55,852 | 2997 | proxy.proxy, handle_switch, 231 | DEBUG | no data from switch read
2021-05-05 16:27:55,853 | 2997 | proxy.proxy, handle_switch, 246 | INFO | Close the connection and do exit processing
2021-05-05 16:27:55,853 | 2997 | proxy.proxy, handle_switch, 229 | DEBUG | read b''
2021-05-05 16:27:55,854 | 2997 | proxy.proxy, handle_switch, 231 | DEBUG | no data from switch read
2021-05-05 16:27:55,854 | 2997 | proxy.proxy, handle_switch, 246 | INFO | Close the connection and do exit processing
2021-05-05 16:27:56,756 | 2997 | root, <module>, 51 | INFO | keyboardInterrupt : 
2021-05-05 16:27:56,764 | 2997 | asyncio, default_exception_handler, 1707 | ERROR | Task was destroyed but it is pending!
task: <Task pending name='Task-42' coro=<ControllerHandler.handle_controller() running at /home/shu/Network/ofcapture/proxy/proxy.py:335> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7faccdd59f10>()]>>
2021-05-05 16:27:56,766 | 2997 | proxy.proxy, handle_controller, 349 | INFO | Close the connection and do exit processing
2021-05-05 16:27:56,766 | 2997 | proxy.proxy, handle_controller, 349 | INFO | Close the connection and do exit processing
2021-05-05 16:27:56,769 | 2997 | asyncio, default_exception_handler, 1707 | ERROR | Task was destroyed but it is pending!
task: <Task pending name='Task-47' coro=<ControllerHandler.handle_controller() done, defined at /home/shu/Network/ofcapture/proxy/proxy.py:317> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7faccdd59790>()]>>
2021-05-05 16:27:56,770 | 2997 | proxy.proxy, handle_controller, 349 | INFO | Close the connection and do exit processing
2021-05-05 16:27:56,771 | 2997 | asyncio, default_exception_handler, 1707 | ERROR | Task was destroyed but it is pending!
task: <Task pending name='Task-48' coro=<ControllerHandler.handle_controller() done, defined at /home/shu/Network/ofcapture/proxy/proxy.py:317> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7faccdd59b20>()]>>
2021-05-05 16:27:56,772 | 2997 | proxy.proxy, handle_controller, 349 | INFO | Close the connection and do exit processing
2021-05-05 16:27:56,778 | 2997 | asyncio, default_exception_handler, 1707 | ERROR | Task was destroyed but it is pending!
task: <Task pending name='Task-51' coro=<ControllerHandler.handle_controller() done, defined at /home/shu/Network/ofcapture/proxy/proxy.py:317> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7faccdd592b0>()]>>
2021-05-05 16:27:56,779 | 2997 | proxy.proxy, handle_controller, 349 | INFO | Close the connection and do exit processing
2021-05-05 16:27:56,779 | 2997 | asyncio, default_exception_handler, 1707 | ERROR | Task was destroyed but it is pending!
task: <Task pending name='Task-56' coro=<ControllerHandler.handle_controller() done, defined at /home/shu/Network/ofcapture/proxy/proxy.py:317> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7faccdd59850>()]>>
2021-05-05 16:27:56,780 | 2997 | proxy.proxy, handle_controller, 349 | INFO | Close the connection and do exit processing
2021-05-05 16:27:56,780 | 2997 | asyncio, default_exception_handler, 1707 | ERROR | Task was destroyed but it is pending!
task: <Task pending name='Task-57' coro=<ControllerHandler.handle_controller() done, defined at /home/shu/Network/ofcapture/proxy/proxy.py:317> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7faccdd598e0>()]>>
2021-05-05 16:27:56,781 | 2997 | proxy.proxy, handle_controller, 349 | INFO | Close the connection and do exit processing
2021-05-05 16:27:56,782 | 2997 | asyncio, default_exception_handler, 1707 | ERROR | Task was destroyed but it is pending!
task: <Task pending name='Task-60' coro=<ControllerHandler.handle_controller() done, defined at /home/shu/Network/ofcapture/proxy/proxy.py:317> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7faccdd3c280>()]>>
2021-05-05 16:27:56,789 | 2997 | proxy.proxy, handle_controller, 349 | INFO | Close the connection and do exit processing
2021-05-05 16:27:56,792 | 2997 | asyncio, default_exception_handler, 1707 | ERROR | Task was destroyed but it is pending!
task: <Task pending name='Task-65' coro=<ControllerHandler.handle_controller() done, defined at /home/shu/Network/ofcapture/proxy/proxy.py:317> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7faccdd3c520>()]>>
2021-05-05 16:27:56,801 | 2997 | proxy.proxy, handle_controller, 349 | INFO | Close the connection and do exit processing
2021-05-05 16:27:56,802 | 2997 | asyncio, default_exception_handler, 1707 | ERROR | Task was destroyed but it is pending!
task: <Task pending name='Task-66' coro=<ControllerHandler.handle_controller() done, defined at /home/shu/Network/ofcapture/proxy/proxy.py:317> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7faccdd3ca90>()]>>
2021-05-05 16:27:56,802 | 2997 | proxy.proxy, handle_controller, 349 | INFO | Close the connection and do exit processing
2021-05-05 16:27:56,803 | 2997 | asyncio, default_exception_handler, 1707 | ERROR | Task was destroyed but it is pending!
task: <Task pending name='Task-69' coro=<ControllerHandler.handle_controller() done, defined at /home/shu/Network/ofcapture/proxy/proxy.py:317> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7faccdd3ce80>()]>>
2021-05-05 16:27:56,804 | 2997 | proxy.proxy, handle_controller, 349 | INFO | Close the connection and do exit processing
2021-05-05 16:27:56,805 | 2997 | asyncio, default_exception_handler, 1707 | ERROR | Task was destroyed but it is pending!
task: <Task pending name='Task-74' coro=<ControllerHandler.handle_controller() done, defined at /home/shu/Network/ofcapture/proxy/proxy.py:317> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7faccdce9640>()]>>
2021-05-05 16:27:56,806 | 2997 | proxy.proxy, handle_controller, 349 | INFO | Close the connection and do exit processing
2021-05-05 16:27:56,806 | 2997 | asyncio, default_exception_handler, 1707 | ERROR | Task was destroyed but it is pending!
task: <Task pending name='Task-75' coro=<ControllerHandler.handle_controller() done, defined at /home/shu/Network/ofcapture/proxy/proxy.py:317> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7faccdce9490>()]>>
